### ISSUE TITLE
error running convertAlignment.pl

### ISSUE THREAD

**Issue by ghost** [lskatz/lskScripts#1]
Hi I am getting following error message. I would be grateful if you could help me fix this. 
Bareword found where operator expected at convertAlignment.pl line 6, near ""en" class"
    (Missing operator before class?)
Bareword found where operator expected at convertAlignment.pl line 25, near "<title>lskScripts"
    (Missing operator before lskScripts?)
Can't modify numeric lt (<) in scalar assignment at convertAlignment.pl line 6, near ""en" class"
syntax error at convertAlignment.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 53 at convertAlignment.pl line 25.

**Comment by lskatz** [comment]
I don't have `<br>` in my script anywhere and I don't have the actual word `lskScripts` in my script anywhere... are you sure you downloaded the correct file?

**Comment by ghost** [comment]
I am sure I downloaded convertAlignment.pl file. Now when I copied and pasted the script into a new file, it is working great. Thank you.
